# Generated by Django 4.1.12 on 2023-11-08 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubRepositoryModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('homepage', models.URLField()),
                ('language', models.CharField(max_length=255)),
                ('archived', models.BooleanField()),
                ('fork', models.BooleanField()),
                ('open_issues', models.IntegerField()),
                ('watchers_count', models.IntegerField()),
                ('url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
