# Generated by Django 4.1.12 on 2023-11-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubrepositorymodel',
            old_name='open_issues',
            new_name='open_issues_count',
        ),
    ]
