# Generated by Django 4.1.12 on 2023-11-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_open_issues_githubrepositorymodel_open_issues_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GitHubRepositoryModel',
        ),
    ]
