# Generated by Django 4.1.12 on 2023-11-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubrepositorymodel',
            name='fork',
        ),
        migrations.AddField(
            model_name='githubrepositorymodel',
            name='branch_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubrepositorymodel',
            name='branches',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubrepositorymodel',
            name='code_freq',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubrepositorymodel',
            name='collaborators',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubrepositorymodel',
            name='collaborators_access',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubrepositorymodel',
            name='commits',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubrepositorymodel',
            name='forks_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubrepositorymodel',
            name='owner',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
