# Generated by Django 4.1.12 on 2023-11-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_githubrepositorymodel_fork_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepositorymodel',
            name='branches',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='githubrepositorymodel',
            name='code_freq',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='githubrepositorymodel',
            name='collaborators',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='githubrepositorymodel',
            name='commits',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='githubrepositorymodel',
            name='owner',
            field=models.JSONField(default={}),
        ),
    ]
