# Generated by Django 4.1.12 on 2023-11-10 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_githubrepositorymodel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepositorymodel',
            name='cached_at',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
