# Generated by Django 4.1.12 on 2023-11-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_githubrepositorymodel_cached_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubrepositorymodel',
            old_name='commits',
            new_name='commit_activity',
        ),
    ]
