# Generated by Django 4.1.12 on 2023-11-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_commits_githubrepositorymodel_commit_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepositorymodel',
            name='commits',
            field=models.JSONField(default=list),
        ),
    ]
