# Generated by Django 4.1.12 on 2023-11-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_githubrepositorymodel_commits'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepositorymodel',
            name='pull_requests_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='githubrepositorymodel',
            name='open_issues_count',
            field=models.IntegerField(default=0),
        ),
    ]
