# Generated by Django 4.1.12 on 2023-11-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_githubrepositorymodel_pull_requests_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepositorymodel',
            name='pull_requests',
            field=models.JSONField(default=list),
        ),
    ]
