# Generated by Django 4.1.12 on 2023-11-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_githubrepositorymodel_pull_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepositorymodel',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
